install.packages(c(
  'abind', 'acepack', 'actuar', 'ada', 'ade4', 'adehabitatLT', 'adehabitatMA', 'ADGofTest', 'AER',
    'AGD', 'agricolae', 'AICcmodavg', 'akima', 'alr4',
    'amap', 'Amelia', 'animation','ape', 'arm', 'arules', 'arulesViz', 'ascii', 'assertthat',
  'base64enc', 'BayesX', 'BB', 'bbmle', 'bdsmatrix', 'betareg', 'BH', 'biclust', 'biglm', 'bit',
    'bit64', 'bitops', 'BMA', 'BradleyTerry2', 'brew', 'brglm', 'BRugs',
  'ca', 'caTools', 'cacheSweave', 'Cairo', 'cairoDevice', 'candisc', 'car', 'caret', 'catdata',
    'cba', 'ccaPP', 'cem', 'chemometrics', 'chron', 'CircStats', 'circular', 'clhs', 'clue',
    'coda', 'combinat',
    'CompQuadForm', 'coin', 'colorspace', 'copula', 'corpcor', 'corrgram', 'corrplot', 'coxme',
    'cmprsk', 'crayon', 'cshapes', 'cubature', 'Cubist', 'curl',
  'd3Network', 'DAAG', 'data.table', 'date', 'DBI', 'deldir', 'denstrip', 'DEoptimR',
    'DescTools', 'deSolve', 'devtools', 'dfoptim', 'diagram', 'dichromat', 'DierckxSpline',
    'digest', 'diptest',
    'distrom', 'DistributionUtils', 'diveMove', 'dmr', 'doBy', 'doMC', 'doParallel', 'doSNOW',
    'dynlm', 'dplyr',
  'e1071', 'earth', 'Ecdat', 'Ecfun', 'effects', 'elasticnet', 'ellipse',
    'emdbook', 'entropy', 'ergm', 'evaluate', 'expm', 'expsmooth',
  'Fahrmeir', 'fastICA', 'fastmatch', 'fBasics', 'fda', 'fdrtool', 'fft',
    'fields', 'filehash', 'fit.models', 'flexclust', 'flexmix', 'fma',
    'FMStable', 'FNN', 'foreach', 'forecast', 'formatR', 'Formula', 'forward', 'fpp', 'fracdiff',
    'FRB', 'fTrading', 'fts', 
  'gam', 'GAMBoost', 'gamlr', 'gamlss', 'gamlss.data', 'gamlss.dist', 'gamm4',
    'gclus', 'gdata', 'gbm', 'gee', 'geepack', 'GeneralizedHyperbolic',
    'geoR', 'geoRglm', 'geosphere', 'git2r', 'GGally', 'ggm', 'ggplot2', 'glasso', 'glmmML',
    'glmnet',
    'gmodels', 'gmp', 'gnm' , 'gof', 'goftest', 'googleVis', 'GPArotation', 'gpclib', 'gplots',
    'grid', 'gridBase', 'gridExtra', 'gridSVG', 'grImport', 'gsl', 'gss', 'gstat',
    'gtable', 'gtools', 'gWidgets', 'gWidgetsRGtk2',
  'hash', 'hdi', 'heplots', 'hexbin', 'highlight', 'highr', 'Hmisc', 'HSAUR', 'htmltools', 'httpuv',
    'httr', 'huge',
  'igraph', 'igraphdata', 'ineq', 'inline', 'intergraph', 'intervals', 'iplots', 'ipred', 'isa2',
    'ISOcodes', 'ISwR', 'iterators', 'itertools', 'its',
  'jpeg', 'jsonlite', 
  'kernlab', 'kinship2', 'kknn', 'klaR', 'knitr', 'ks',
  'labeling', 'Lahman', 'lars', 'lattice', 'latticeExtra', 'lava', 'lava.tobit', 'lavaan',
    'lavaan.survey', 'lazyeval', 'leaps', 'LearnBayes', 'lhs', 'LICORS', 'linprog', 'lintr',
    'lisrelToR',
    'lme4', 'lmtest', 'locfit', 'logcondens', 'logspline', 'lokern', 'longmemo', 'lpSolve', 'lqa',
    'lubridate',
  'magic', 'magrittr', 'mapdata', 'mapproj', 'maps', 'maptools', 'maptpx', 'markdown',
    'Matching', 'MatchIt', 'Matrix', 'matrixcalc', 'MatrixModels', 'maxLik', 'maxlike',
    'MBESS', 'mboost',
    'mclust', 'MCMCpack', 'mda', 'MEMSS', 'memoise', 'mets', 'microbenchmark',
    'mi', 'mice', 'mime', 'minqa', 'misc3d', 'miscTools', 'mitools', 'mix', 'mlbench', 'mlmRev',
    'mlogit', 'mnormt', 'modeltools', 'mondate', 'MplusAutomation', 'MPV',
    'mratios', 'multcomp', 'multicool', 'MuMIn', 'munsell', 'mvtnorm',
    'mvnormtest',
  'ncdf', 'ncdf4', 'network', 'neuralnet', 'nloptr', 'NLP', 'nnet', 'nnls', 'nor1mix', 'np',
    'numDeriv', 'nws', 'nycflights13',
  'openair', 'OpenMx', 'optextras', 'optmatch', 'optimx', 'ordinal', 'oz',
  'pamr', 'pan', 'partitions', 'party', 'pbivnorm', 'PBSmapping', 'pcaPP', 'penalized',
    'pbkrtest',  'PerformanceAnalytics', 'permute', 'pmg', 'pixmap', 'pkgKitten', 'PKPDmodels',
    'playwith', 'plm', 'plotmo', 'plotrix', 'pls',  'plyr', 'pmml', 'pmmlTransformations',
    'png', 'poLCA',  'polyclip',
    'polspline', 'polycor', 'polynom', 'PolynomF',
    'prefmod', 'pROC', 'prodlim', 'profileModel', 'proto', 'proxy', 'pryr', 'pscl',
    'pspline', 'psych',
  'qgraph', 'gsubfn', 'quadprog', 'quantmod', 'quantreg', 'qvcalc',
  'R.cache', 'R.devices', 'R.matlab', 'R.methodsS3', 'R.oo', 'R.rsp', 'R.utils', 'R2jags', 'R2HTML',
    'R2OpenBUGS', 'R2wd', 'R2WinBUGS', 'R6', 'RandomFields', 'randomForest', 'randomForestSRC',
    'RANN', 'raster', 'rasterVis', 'rattle', 'rbenchmark',  'rbounds', 'Rcgmin', 'RcmdrMisc',
    'RColorBrewer', 'Rcmdr', 'Rcpp',
    'RcppArmadillo', 'RcppEigen', 'Rcsdp', 'RCurl', 'RDCOMClient', 'relations', 'relimp', 'reshape',
    'reshape2', 'rex', 'rgenoud', 'rgeos', 'rgdal', 'rggobi', 'rgl', 'Rglpk', 'RgoogleMaps',
    'RGraphics', 'RGtk2', 'RH2', 'RItools',
    'rjags', 'rJava', 'RJDBC', 'rjson', 'RJSONIO', 'rlecuyer', 'Rmalschains', 'rmarkdown', 'rmeta',
    'Rmpfr', 'Rmpi', 'rms', 'RMySQL', 'rockchalk', 'ROCR', 'RODBC', 'robust', 'robustbase',
    'roxygen2', 'rpanel', 'rpart', 'rpart.plot', 'rpf', 'RPostgreSQL', 'rPython', 'rrcov', 'RSNNS',
    'Rsolnp',  'rsprng', 'RSQLite', 'RSQLite.extfuns', 'rstudioapi', 'RSVGTipsDevice',
    'Rsymphony', 'stringr', 'rtiff', 'rugarch', 'RUnit', 'rversions', 'rvest', 'Rvmmin',
  'sampleSelection', 'sandwich', 'scagnostics', 'scales', 'scalreg', 'scatterplot3d', 'scrypt',
    'sem', 'selectr', 'semPlot', 'semTools', 'sendplot', 'seriation', 'setRNG', 'sets', 'sfsmisc',
    'shape', 'shapefiles', 'shiny', 'simsem', 'SimComp', 'SkewHyperbolic',
    'slam', 'Sleuth2', 'sm', 'sn', 'sna', 'snow', 'SnowballC', 'snowfall', 'soiltexture', 'som',
    'sp', 'spacetime', 'spam', 
    'SparseM', 'spatstat', 'spd', 'spdep', 'spacetime', 'spatstat', 'splancs', 'splines', 'spls',
    'sqldf',
    'stabs', 'StanHeaders', 'stashR', 'statmod', 'statnet.common', 'stabledist', 'stringdist',
    'stringi', 'stringr', 'strucchange', 'subselect', 'superpc', 'SuppDists', 'survey', 'survival',
    'svd', 'svGUI', 'svUnit', 'symbols', 'systemfit',
  'tables', 'tcltk2', 'TeachingDemos',  'tensor', 'testit', 'testthat', 'textir', 'texreg', 'tgp',
    'TH.data', 'tikzDevice', 'timeDate', 'timereg', 'timeSeries', 'tis', 'tkrplot', 'tm', 'tnet', 
    'tree', 'tripack', 'trust', 'truncnorm', 'truncreg', 'TSA', 'tseries', 'TSP', 'TTR', 'tweedie',
  'ucminf', 'unmarked', 'urca',
  'VarianceGamma', 'vcd', 'vcdExtra', 'vegan', 'venneuler', 'VGAM', 'VGAMdata', 'vioplot',
    'vrmlgen',
  'WhatIf', 'whisker', 'wordcloud', 
  'xlsx', 'xlsxjars', 'XML', 'xtable', 'xts',
  'yaml', 'yaImpute',
  'Zelig', 'zipcode', 'zoo'), dependencies = TRUE)

#install Rtools before running these
library(devtools)
install_github('ramnathv/rcharts')
install_github('ramnathv/slidify')
install_github('ramnathv/slidifyLibraries')
install_github('rstudio/shinyapps')
install_github("amplab-extras/SparkR-pkg", subdir="pkg")